#!/bin/bash

# Colors
# Up
# echo "#99CC99"
# Dormant
# echo "#F99157"
# Down
# echo "#F2777A"

connected(){
    nmcli d s | grep "$1" | awk '{print $3}'
}

get_connection(){
    nmcli d s | grep "$1" | awk '{$1=$2=$3=""; print $0}' | xargs
}

get_devices(){
    nmcli d | grep connected | while read -r line ; do
    if [[ $(echo "$line" | awk '{print $2}') == "ethernet" ]]; then
        echo "$(echo "$line" | awk '{print $1}')"
    elif [[ $(echo "$line" | awk '{print $2}') == "wifi" ]]; then
        echo "$(echo "$line" | awk '{print $1}')"
    fi
    done
}

hackbook(){
for device in $(get_devices); do
    status=$(connected "$device")
    conn=$(get_connection "$device")
    if [[ $status == "connected" ]]; then
        echo " $device/$conn"
        echo " $device/$conn"
        echo "#99CC99"
        break
    elif [[ $status == "disconnected" ]]; then
        echo " $device/"
        echo " $device/"
        echo "#F2777A"
        break
    fi
done
}

theia(){
    CONN=$(netctl-auto list | grep "*" | tr -d "* ")
    if [[ $CONN ]]; then
        echo " $CONN"
        echo " $CONN"
        echo "#99CC99"
    fi
}


if [[ $(hostname) == "hackbook" ]]; then
    hackbook
else
    theia
fi
